### ISSUE TITLE
Incompatible dependencies with tensorflow

### ISSUE THREAD

**Issue by gehring** [NeilGirdhar/tjax#1]
`tjax` requires `numpy>=1.21` which seems to conflict with `tensorflow`'s requirement of `numpy~=1.19.2`. I don't think needing both jax and tensorflow together is an uncommon use case. Jax functions can be converted to tensorflow (e.g., `jax.experimental.jax2tf`) which allows the use of, amongst other things, tensorflow's model saving/loading machinery.

**Comment by NeilGirdhar** [comment]
Are you installing tensorflow with tjax?  I don't see any indirect dependency on tjax on my end.

**Comment by NeilGirdhar** [comment]
FYI: For tensorflow and numpy, we're waiting on https://github.com/tensorflow/tensorflow/pull/48935

**Comment by gehring** [comment]
Yes, I'm installing tensorflow and tjax in the same python environment. Yeah, I noticed tensorflow is behind. I don't think it's worth changing anything in tjax now since I can just use an older version and tensorflow will eventually catch up. I just wanted to bring to your attention since you might not use tensorflow and jax in the same environment.

**Comment by NeilGirdhar** [comment]
@gehring Okay, thanks!  I have installed tjax and tensorflow side-by-side, along with numpy 1.21.  I think the tensorflow problems revolve around tensors whose shapes are themselves tensors.  I don't use anything like that.

**Comment by NeilGirdhar** [comment]
Looks like https://github.com/tensorflow/tensorflow/pull/48935 was essentially merged.  Should be good next Tensorflow version.
