### ISSUE TITLE
Optimizers and other pytree libraries

### ISSUE THREAD

**Issue by cgarciae** [NeilGirdhar/tjax#2]
Hey @NeilGirdhar !

I have a keen interest on having Pytree ecosystem in JAX as IMO it makes many things simpler without loosing too much generality.

I've created this library called [Treeo](https://github.com/cgarciae/treeo) which is somewhat similar to your `dataclass` implementation, while it also support dataclasses, it has some additional features.

Would like to know if you are interested in collaborating on these topics, I am specially interested in Pytree Optimizers that could integrate with [Treex](https://github.com/cgarciae/treex) and [Elegy](https://github.com/poets-ai/elegy). Happy to have a chat if you have the time.

**Comment by NeilGirdhar** [comment]
Hello @cgarciae!

I recognize your name from the Jax github issue tracker.  I didn't realize you had any Jax projects—let alone three!  It's going to take me some time to digest everything you've done so far, but it looks great.  It's really interesting to see how we're all figuring out the best way to do machine learning with Jax.  I'm definitely interested in collaborating on tools and libraries.

I think what I'll start wtih is read over your libraries and ask questions and share my thoughts.  If you're interested, I'd appreciate any thoughts and suggestions you might have on my libraries (this one, and https://github.com/NeilGirdhar/efax).  We both have a lot of experience with Jax, but maybe different intuitions?

I definitely have time to chat with you.  Let me know.

**Comment by cgarciae** [comment]
Hey @NeilGirdhar , `efax` looks really cool! I am not too familar with probabilistic modeling but could rather give you feedback on the JAX related abstractions. I will try to get a closer look before we talk to give you some feedback.

Want to hop into [elegy's discord](https://discord.gg/tTE6NytZgw) and we can find a time for a call? Else feel free to email me at: `cgarcia.e88@gmail.com`

**Comment by NeilGirdhar** [comment]
Nice meeting with you!
